--2014-02-28 11:57:52--  http://stash.osgconnect.net/+sthapa/cvmfs-root.tar.gz
Resolving stash.osgconnect.net... 192.170.227.197
Connecting to stash.osgconnect.net|192.170.227.197|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://raw.stash.osgconnect.net/+sthapa/cvmfs-root.tar.gz [following]
--2014-02-28 11:57:52--  http://raw.stash.osgconnect.net/+sthapa/cvmfs-root.tar.gz
Resolving raw.stash.osgconnect.net... 192.170.227.197
Reusing existing connection to stash.osgconnect.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 38883 (38K) [application/x-gzip]
Saving to: `cvmfs-root.tar.gz'

     0K .......... .......... .......... .......              100%  231M=0s

2014-02-28 11:57:52 (231 MB/s) - `cvmfs-root.tar.gz' saved [38883/38883]

/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/utilities/createUserASetup.sh: line 40: /.asetup: Permission denied
140228 12:00:35 414 Xrd: ReadPartialAnswer: Failed to read msg from connmgr (server [faxbox.mwt2.org:1094]). Retrying ...
140228 12:00:35 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:06 425 Xrd: XrdClientMessage::ReadRaw: Failed to read header (8 bytes).
140228 12:03:18 414 Xrd: XrdClientSock::RecvRaw: Error reading from socket: Connection reset by peer
140228 12:03:18 414 Xrd: DoHandShake: Failed to read 4 bytes. Retrying ...
140228 12:03:18 414 Xrd: GetAccessToSrv: HandShake failed with server [faxbox.mwt2.org:1094]
140228 12:03:18 414 Xrd: GoToAnotherServer: Error handshaking to [faxbox.mwt2.org:1094]
140228 12:03:23 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:23 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:23 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:23 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:28 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:28 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:28 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:28 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:33 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:33 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:33 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:33 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:38 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:38 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:38 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:38 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:43 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:43 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:43 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:43 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:48 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:48 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:48 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:48 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:53 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:53 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:53 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:53 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:03:58 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:03:58 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:03:58 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:03:58 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:03 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:03 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:03 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:03 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:08 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:08 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:08 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:08 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:13 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:13 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:13 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:13 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:18 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:18 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:18 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:18 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:23 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:23 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:23 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:23 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:28 414 Xrd: HandleServerError: Communication error with server [faxbox.mwt2.org:1094]. Rebouncing here.
140228 12:04:28 414 Xrd: Connect: can't open connection to [faxbox.mwt2.org:1094]
140228 12:04:28 414 Xrd: XrdNetFile: Error creating logical connection to faxbox.mwt2.org:1094
140228 12:04:28 414 Xrd: GoToAnotherServer: Error connecting to [faxbox.mwt2.org:1094
140228 12:04:33 414 Xrd: SendGenCommand: Too many redirections for request  kXR_open. Aborting command.
140228 12:04:33 414 Xrd: Open: Error opening the file /user/sthapa/FDR/user.flegger.MWT2.data12_8TeV.00212172.physics_Muons.merge.NTUP_SMWZ.f479_m1228_p1067_p1141_tid01007411_00/NTUP_SMWZ.01007411._000033.MWT2.root.1 on host faxbox.mwt2.org:1094
Error in <TXNetFile::CreateXClient>: open attempt failed on root://faxbox.usatlas.org//user/sthapa/FDR/user.flegger.MWT2.data12_8TeV.00212172.physics_Muons.merge.NTUP_SMWZ.f479_m1228_p1067_p1141_tid01007411_00/NTUP_SMWZ.01007411._000033.MWT2.root.1

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 2 (Thread 0x2b79843ae700 (LWP 424)):
#0  0x00000031058accdd in nanosleep () from /lib64/libc.so.6
#1  0x00000031058acb50 in sleep () from /lib64/libc.so.6
#2  0x00002b7983f74e3c in GarbageCollectorThread (arg=0xde2d50, thr=<value optimized out>) at /afs/slac/public/software/scalla/releases/v3.2.7/xrootd-3.2.7/src/XrdClient/XrdClientConnMgr.cc:73
#3  0x00002b7983cf8b0f in XrdSysThread_Xeq (myargs=0xd8bf40) at /afs/slac/public/software/scalla/releases/v3.2.7/xrootd-3.2.7/src/XrdSys/XrdSysPthread.cc:67
#4  0x00000031060079d1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000031058e8b6d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b7983679080 (LWP 414)):
#0  0x00000031058ac8fd in waitpid () from /lib64/libc.so.6
#1  0x000000310583e909 in do_system () from /lib64/libc.so.6
#2  0x000000310583ec40 in system () from /lib64/libc.so.6
#3  0x00002b797e37e7cc in TUnixSystem::StackTrace() () from /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/5.34.14-x86_64-slc6-gcc4.7/lib/libCore.so
#4  0x00002b797e381003 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/5.34.14-x86_64-slc6-gcc4.7/lib/libCore.so
#5  <signal handler called>
#6  0x000000000040420e in readFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, float, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, rootStats*) ()
#7  0x0000000000404b8b in main ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x000000000040420e in readFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, float, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, rootStats*) ()
#7  0x0000000000404b8b in main ()
===========================================================



real	6m43.672s
user	0m1.279s
sys	0m0.577s
